#!/usr/bin/env bash
# This script configures a Nginx server with a custom 404 page

# Install Nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Start Nginx
sudo service nginx start

# Create a custom 404 page
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html

# Configure Nginx to use the custom 404 page
echo "server {
    listen 80;
    server_name _;
    error_page 404 /custom_404.html;
    location = /custom_404.html {
        root /usr/share/nginx/html;
        internal;
    }
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" | sudo tee /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
sudo service nginx restart
