#!/usr/bin/env bash
# This script displays the PID and process name of
# processes whose name contains the word "bash".
# Use the pgrep command to find the PIDs of
#   processes whose name contains "bash".
# The -l option displays the process name
#  along with the PID.
pgrep -l bash

