#!/usr/bin/env bash
# This script displays all active IPv4 IPs on the machine it's executed on

# Use ip command to get IPs, grep to filter for inet (IPv4), and awk to print the IP
ip addr show | grep -o 'inet [0-9]\+\.[0-9]\+\.[0-9]\+\.[0-9]\+' | awk '{print $2}'
