#!/usr/bin/env bash
# This script configures the container to run Nginx as the ngnix user
# and listen on port 8080

#Stop the Nginx service
service nginx stop

#Change the user in the Nginx configuration
sed -i 's/user root;/user nginx;/' /etc/nginx/nginx.conf

# Change the listen directive to listen on port 8080
sed -i 's/listen 80 default_server;/listen 8080 default_server;/' /etc/nginx/sites-available/default

#Start the Nginx service
service nginx start
